FROM docker.elastic.co/logstash/logstash:7.7.0
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
RUN /usr/share/logstash/bin/logstash-plugin install logstash-output-mongodb
ADD pipeline/ /usr/share/logstash/pipeline/
ADD config/ /usr/share/logstash/config/